name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build N push Docker Image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DkrHub_USERNAME }}
          password: ${{ secrets.DkrHub_PASSWORD }}
          repository: ${{ github.repository }}
          tag_with_ref: true
          tag_with_sha: false
          tags: ${{ github.sha }}
      - name: Deploy SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo ${{ secrets.DATABASE_USERNAME }}
            docker login -u ${{ secrets.DkrHub_USERNAME }} -p ${{ secrets.DkrHub_PASSWORD }}
            docker rm -f gonzu-api mongodb
            docker run -d --rm -p 27017:27017 --name mongodb --network gonzu_bridge_network -v /app/mongodb/data:/data/db -e MONGO_INITDB_ROOT_USERNAME=${{ secrets.DATABASE_USERNAME }} -e MONGO_INITDB_ROOT_PASSWORD=${{ secrets.DATABASE_PASSWORD }} mongo
            docker run -d --rm -p 4000:4000 --name gonzu-api \
              -e MONGO_URI=${{ secrets.MONGO_URI }} -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} \
              -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} -e S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }} \
              -e S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }} -e S3_REGION=${{ secrets.S3_REGION }} \
              -e S3_BUCKET=${{ secrets.S3_BUCKET }} \
              ${{ github.repository }}
